remote_theme: daattali/beautiful-jekyll

# --- Basic options --- #

# Name of website
title: AttaliTech Ltd

# Short description of your site
description: Expert R-Shiny Consultant

# Your name to show in the footer
author: AttaliTech Ltd

# --- List of links in the navigation bar --- #

navbar-links:
  Blog: "https://deanattali.com/"
  Open-Source: "https://deanattali.com/projects"
  Schedule meeting: "https://calendly.com/attalitech/meeting"
  Contact: "https://deanattali.com/contact"

# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "dean@attalitech.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  stackoverflow: "3943160/daattali"
  calendly: "attalitech/meeting"
# --- General options --- #

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "AttaliTech.com"

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#404040"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-59820529-1"

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM


# Exclude these files from production siteML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
